# Lecture 4

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'2.1.3'
  matplotlib version:'3.10.0'


## Vector Operations

* NumPy operations are done on an <b><font color="green">element-by-element</font></b> basis

In [2]:
# Regular Python: '+'/'*' 
N = 5
x = [i for i in range(N)]
y = N*[1]
print(f"  x  :{x}")
print(f"  y  :{y}")
print(f"  x+y:{x+y}")  # extend method for lists

  x  :[0, 1, 2, 3, 4]
  y  :[1, 1, 1, 1, 1]
  x+y:[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]


In [3]:
# Numpy's addition
x = np.array(x)
y = np.array(y)
print(f"  x  :\n{x}")
print(f"  y  :\n{y}")
print(f"  x+y:\n{x+y}")

  x  :
[0 1 2 3 4]
  y  :
[1 1 1 1 1]
  x+y:
[1 2 3 4 5]


<b>Note:</b>: Python lists vs. Numpy ndarrays differences<br>
* The '*' operator 
* Assigment in slices

**Examples**

In [4]:
# Numpy's Multiplication
rng = rnd.default_rng()
x = rng.integers(3,10,(4,4))
y = rng.integers(1,5,(4,4))
print(f"  x:\n{x}\n")
print(f"  y:\n{y}\n")
print(f"  x*y:\n{x*y}\n")

  x:
[[8 5 3 5]
 [3 8 8 3]
 [3 8 3 6]
 [6 5 5 7]]

  y:
[[3 3 1 1]
 [1 3 4 1]
 [3 4 4 2]
 [1 4 2 2]]

  x*y:
[[24 15  3  5]
 [ 3 24 32  3]
 [ 9 32 12 12]
 [ 6 20 10 14]]



In [ ]:
# b. Boolean operators working on NumPy arrays
rng = rnd.default_rng()
x = rng.integers(4,10,(12))
y = rng.integers(4,10,(12))
print(f"  x={x}")
print(f"  y={y}\n")
print(f"  ==      : {x==y}")
print(f"  !=      : {x!=y}")
print(f"  not(!=) : {~(x!=y)}")
print(f"  >=      : {x>=y}")
print(f"  x>7     : {x>7}")

### Combining boolean operators for ndarray objects


<font color="green"><b>Regular python</b></font> : 
* and  
* or  (inclusive or)
* not (negation operator)
* !=  (exclusive or)
 

In [ ]:
# Combining boolean operators as in REGULAR'Python' way -> ERROR
# x < 5 or y>7
# (Due to DIFFERENT syntax!)

<font color="green"><b>Numpy</b></font>:
* & : and operator
* | : inclusive or operator
* ~ : negation operator
* ^ : exclusive or (xor)

In [7]:
# Combining boolean operators in NumPy
print(f"  x                 : \n{x}\n")
print(f"  y                 : \n{y}\n")
v1 = (x<8) & (x>4)
print(f"  (x<8) & (x>4)     : \n{v1}\n")
v2 = (x<6) | (x>7)
print(f"  (x<6) | (x>7)     : \n{v2}\n")
v3 = ~(x==6)
print(f"  ~(x==6)           : \n{v3}\n")
v4 = (x<6) ^ (x<7)   
print(f"  (x<6) ^ (x<7)     : \n{v4}\n")

  x                 : 
[[8 5 3 5]
 [3 8 8 3]
 [3 8 3 6]
 [6 5 5 7]]

  y                 : 
[[3 3 1 1]
 [1 3 4 1]
 [3 4 4 2]
 [1 4 2 2]]

  (x<8) & (x>4)     : 
[[False  True False  True]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]

  (x<6) | (x>7)     : 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [False  True  True False]]

  ~(x==6)           : 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [False  True  True  True]]

  (x<6) ^ (x<7)     : 
[[False False False False]
 [False False False False]
 [False False False  True]
 [ True False False False]]



### How to perform matrix multiplications in Numpy?

* Numpy operators work in an el. by el. fashion
* To perform matrix multiplications in numpy -> <font color="green"><b>np.dot</b></font> function.<br>
  But, you can also use the <font color="green"><b>@</b></font> operator.

**Examples**

In [8]:
# np.dot (1D case)
rng = rnd.default_rng()
a = rng.integers(4,10,(10))
b = rng.integers(1,5,(10))

print(f"  a                 : {a}")
print(f"  b                 : {b}")
print(f"  a.b (dot-product) : {np.dot(a,b)}")
print(f"  a.b (dot.product) : {np.sum(a*b)}")

  a                 : [6 5 6 7 6 5 4 5 6 5]
  b                 : [4 1 3 2 3 3 2 3 2 4]
  a.b (dot-product) : 149
  a.b (dot.product) : 149


In [9]:
# np.dot (2D case) -> Matrix Multiplication
rng = rnd.default_rng()
c = rng.integers(4,10,(2,4))
d = rng.integers(1,5,(4,3))

print(f"  c:\n {c}\n")
print(f"  d:\n {d}\n")
print(f"  c.d (Matrix Multiplication using np.dot):\n {np.dot(c,d)}")
print(f"  c.d (Matrix Multiplication using @ operator):\n {c @ d}")

  c:
 [[8 5 4 6]
 [7 7 9 4]]

  d:
 [[2 1 1]
 [1 2 2]
 [3 2 2]
 [4 4 1]]

  c.d (Matrix Multiplication using np.dot):
 [[57 50 32]
 [64 55 43]]
  c.d (Matrix Multiplication using @ operator):
 [[57 50 32]
 [64 55 43]]


## Broadcasting

Let's start with a few simple examples/tests ...

**Example 1**

In [10]:
x = np.arange(1,5)
y = np.arange(10,50,10)
print(f"  x      : {x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y      : {y}")
print(f"  y.shape: {y.shape}\n")
print(f"  x+y        : {x+y}")
print(f"  (x+y).shape: {(x+y).shape}")

  x      : [1 2 3 4]
  x.shape: (4,)

  y      : [10 20 30 40]
  y.shape: (4,)

  x+y        : [11 22 33 44]
  (x+y).shape: (4,)


**Example 2**

In [11]:
x = np.arange(1,5)
y = np.arange(1,4)
print(f"  x      : {x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y  : {y}".format(y))
print(f"  y.shape: {y.shape}\n")
print(f"  x+y: {x+y}")

  x      : [1 2 3 4]
  x.shape: (4,)

  y  : [1 2 3]
  y.shape: (3,)



ValueError: operands could not be broadcast together with shapes (4,) (3,) 

**Example 3**

In [12]:
# Example 3:
rng = rnd.default_rng()
x = np.arange(1,5)
y = rng.integers(0,11,(3,4))
print(f"  x  : \n{x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y  : \n{y}")
print(f"  y.shape: {y.shape}\n")
print(f"  x+y: \n{x+y}")

  x  : 
[1 2 3 4]
  x.shape: (4,)

  y  : 
[[ 9  7  6  2]
 [ 4  7  8  9]
 [ 4  8 10  6]]
  y.shape: (3, 4)

  x+y: 
[[10  9  9  6]
 [ 5  9 11 13]
 [ 5 10 13 10]]


### The rules of broadcasting

* Broadcasting:<br>
  To operate on ndarrays <i>x</i>, <i>y</i> with <b>(seemingly) mismatched</b> shapes 
* Definition:<br>
  Two axes (dimensions) of the ndarrays <i>x</i>, <i>y</i> are <b><font color="green">compatible</font></b><br>
  + If <b>both</b> axes have the <b>same</b> length
  + If <b>one</b> of the axes has length <b>1</b>  
* Algorithm (for broadcasting):
    + If two arrays <i>x</i> & <i>y</i> do <b>NOT</b> have the <b>SAME</b> ndim:<br>
    Let <i>x</i>.ndim < <i>y</i>.ndim, then <b>prepend</b> <b>1</b> to <i>x</i>.shape (<i>mentally!!</i>) 
     until <i>x</i>.ndim==<i>y</i>.ndim  
    + Loop <b>simulataneously</b> over <b>all</b> axes/dimensions of <i>x</i>, <i>y</i>:<br>
      - If axes are compatible:<br>
        + If they have <b><font color="green">same</font></b> length => <b><font color="green">OK</font></b> <br>
        + Else: increase length of smallest axis to the length of the largest axis => <b><font color="green">OK</font></b>
      - Else:<br> 
          <b><font color="red">Error</font></b>: Impossible to broadcast

**Examples**

In [13]:
# Example 1
# Res: x: 4 x 1
#      y:     5
# -------------
#    x+y: 4 x 5
#---------------
rng = rnd.default_rng()
x = rng.random(4).reshape(4,1)
y = np.arange(5)
print(f"  x  : \n{x}")
print(f"  y  : \n{y}")
print(f"  x+y: \n{x+y}")

  x  : 
[[0.87512292]
 [0.90104698]
 [0.77182435]
 [0.41796143]]
  y  : 
[0 1 2 3 4]
  x+y: 
[[0.87512292 1.87512292 2.87512292 3.87512292 4.87512292]
 [0.90104698 1.90104698 2.90104698 3.90104698 4.90104698]
 [0.77182435 1.77182435 2.77182435 3.77182435 4.77182435]
 [0.41796143 1.41796143 2.41796143 3.41796143 4.41796143]]


In [14]:
# Example 2
# Res: x: 13 x 1 x 7 x 1
#      y:      8 x 7 x 5
# -------------
#    res: 13 x 8 x 7 x 5
#---------------
x=np.arange(91).reshape((13,1,7,1))
y=np.arange(8*7*5).reshape((8,7,5))
z=x+y
print(f"  x.shape:{x.shape}")
print(f"  y.shape:{y.shape}")
print(f"  z.shape:{z.shape}")

  x.shape:(13, 1, 7, 1)
  y.shape:(8, 7, 5)
  z.shape:(13, 8, 7, 5)


In [15]:
# Example 3:
# Res: x: 3 x 8 x 3
#      y:     3 x 1
# -------------
#    res:     Error !! (8 & 3)
#---------------
x=np.arange(72).reshape((3,8,3))
y=np.arange(9).reshape((3,3))
z=x+y
print(f"  x.shape:{x.shape}")
print(f"  y.shape:{y.shape}")
print(f"  z.shape:{z.shape}")

ValueError: operands could not be broadcast together with shapes (3,8,3) (3,3) 

### Adding & removing singleton dimensions

Axes of dim 1 (singleton dimensions) are a central tool for broadcasting.<br>
There are situations in which, one wants to:
* <b>remove</b> singleton dimensions:
  * use <b><font color="green">numpy.squeeze(a,axis=None)</font></b>
    * a: input data
    * axis : integer/tuple
    * default: all singleton dimensions
  
* <b>add</b> singleton dimensions:
  * use <b><font color="green">numpy.newaxis</font></b>
    * expand the dimension by 1 unit
    * to be added where you want to add the dimension

**Examples**

In [16]:
# np.squeeze() function i.e. Removing Singleton axes
a=np.arange(120).reshape((2,1,3,5,1,4))
print(f"  a.shape: {a.shape}")
b=np.squeeze(a,axis=1)
print(f"  b.shape: {b.shape}")
c=np.squeeze(a,axis=4)
print(f"  c.shape: {c.shape}")
d=np.squeeze(a)
print(f"  d.shape: {d.shape}")

  a.shape: (2, 1, 3, 5, 1, 4)
  b.shape: (2, 3, 5, 1, 4)
  c.shape: (2, 1, 3, 5, 4)
  d.shape: (2, 3, 5, 4)


In [ ]:
# Adding Singleton Axes
a = np.arange(24).reshape((2,3,4))
print(f"  a.shape: {a.shape}")
b = a[np.newaxis,:,:,:]
print(f"  b.shape: {b.shape}")
c = a[np.newaxis,...]
print(f"  c.shape: {c.shape}")
d=a[:,np.newaxis,:,:,np.newaxis]
print(f"  d.shape: {d.shape}")

## Exercises

* Create the following 6x6 matrix $A$ (containing only <font color="green"><b>int32</b></font> elements)):<br>
    $\begin{equation*}A = \begin{pmatrix}
       1 & 1 &  1 &   1 &   1 &   1 \\
       1 & 8 &  1 &   1 &   1 &   1 \\ 
       1 & 1 &  27 &   1 &   1 &   1 \\
       1 & 1 &  1 &   64 &   1 &   1 \\
       1 & 1 &  1 &   1 &  125 &   1 \\
       1 & 1 &  1 &   1 &   1 &   216 
      \end{pmatrix}\end{equation*}$
* Create a new matrix $B$ ($M \times N$) where:
  * $\begin{equation*}B_{ij} =  \frac{1}{X_i - Y_j} \end{equation*}$
  * $X_i$ $\in$ $X$  ($i=0,\ldots,M-1$)<br>
    is a random vector of length $M=9$ 
  * $Y_j$ $\in$ $Y$  ($j=0,\ldots,N-1$)<br>
    is a random vector of length $N=6$ 
    
  Matrices of the type $B$ are known as <font color="blue"><b>Cauchy</b></font> matrices 
  

## Solutions

In [ ]:
# %load ../solutions/ex4.py

## Appendix

* The '*' operator: Python (lists) vs Numpy 

In [ ]:
# Python list '*' operator
print(f"  Python list '*' operator:")
a = [1,2,3,4]
print(f"    a={a}")
b = 5*a     
print(f"    b={b}")   

# Numpy '*' operator :: el-by-el
print(f"  NumPy '*' operator:")
a = np.array([1,2,3,4])
print(f"    a={a}")
b = 5*a
print(f"    b={b}")

* Assigning el: Python (lists) vs Numpy 

In [ ]:
print(f"  Numpy: assignment to slices")
a = np.arange(10)
a[3:7] = 1
print(f"    a={a}")


print(f"  Python: assignment to slices")
try:
    b = np.arange(10).tolist()
    b[3:7] = 1
except Exception as err:
    print(f"    ERROR: {err}\n")   
    
# Solution for Python list!
print(f"   therefore ...")
b = [ 1 if 3<=i<7  else i  for i in b ]
print(f"   b={b}")